In [1]:
import pandas as pd
df = pd.read_csv("iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
# Encoding - convert 3 species into 0, 1, 2
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])

In [3]:
df.sample(10)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
19    20            5.1           3.8            1.5           0.3        0
58    59            6.6           2.9            4.6           1.3        1
35    36            5.0           3.2            1.2           0.2        0
14    15            5.8           4.0            1.2           0.2        0
130  131            7.4           2.8            6.1           1.9        2
112  113            6.8           3.0            5.5           2.1        2
56    57            6.3           3.3            4.7           1.6        1
28    29            5.2           3.4            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
73    74            6.1           2.8            4.7           1.2        1

In [19]:
from sklearn.model_selection import train_test_split

X = df.drop('Species', axis=1)
y = df['Species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state=42)

In [21]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [23]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [25]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [27]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

models = {'Logistic Regression':lr, 'KNN': knn, 'Naive Bayes': nb}

for name, model in models.items():
    y_pred = model.predict(X_test)
    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))

    print("cm:", confusion_matrix(y_test, y_pred))

    print("classification report:", classification_report(y_test, y_pred))

Logistic Regression
Accuracy: 1.0
cm: [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75


KNN
Accuracy: 1.0
cm: [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75


Naive Bayes
Accuracy: 1.0
cm: [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75

In [13]:
print(y_test.values)
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]